./../test/smoke_test.v
./../test/t10_clk_test.v
./../test/t20_tdr_rw.v
./../test/t21_tcr_rw.v
./../test/t22_tsr_rw.v
./../test/t23_all_rw.v
./../test/t11_clk_test_rt.v
./../test/t30_cnt_up_clk2.v
./../test/t31_cnt_up_clk4.v
./../test/t32_cnt_up_clk8.v
./../test/t33_cnt_up_clk16.v
./../test/t34_cnt_up_rst.v
./../test/t35_cnt_up_ovf.v
./../test/t36_cnt_up_ld.v
./../test/t37_cnt_up_fake_ovf.v
./../test/t38_cnt_up_pause.v
./../test/t40_cnt_dw_clk2.v
./../test/t41_cnt_dw_clk4.v
./../test/t42_cnt_dw_clk8.v
./../test/t43_cnt_dw_clk16.v
./../test/t45_cnt_dw_udf.v
./../test/t44_cnt_dw_rst.v
./../test/t46_cnt_dw_fake_udf.v
./../test/t47_cnt_dw_pause.v